// <auto-generated />
using System;
using ExploreMy.Api.Persistence.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace explore_my_backend.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20260828083819_AddHiddenPlaceReview")]
    partial class AddHiddenPlaceReview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("token_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("PendingEmail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pending_email");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId")
                        .HasName("pk_email_verification_token");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_evt_user_id");

                    b.ToTable("email_verification_token", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.FavouritePlace", b =>
                {
                    b.Property<int>("FavouritePlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("favourite_place_id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("LastVisitAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_visit_at");

                    b.Property<double>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PlaceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("place_id");

                    b.Property<string>("PrimaryType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("primary_type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("FavouritePlaceId")
                        .HasName("pk_favourite_place");

                    b.HasIndex("UserId", "PlaceId")
                        .IsUnique()
                        .HasDatabaseName("uq_user_place");

                    b.ToTable("favourite_place", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.FootTrackerLog", b =>
                {
                    b.Property<string>("LogId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("log_id");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DistanceKm")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("distance_km");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ended_at");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<string>("PlaceId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("place_id");

                    b.Property<string>("PrimaryType")
                        .HasColumnType("longtext")
                        .HasColumnName("primary_type");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("LogId")
                        .HasName("pk_foot_tracker_log");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("ix_foot_tracker_log_place_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_foot_tracker_log_user_id");

                    b.ToTable("foot_tracker_log", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.HiddenPlace", b =>
                {
                    b.Property<int>("HiddenPlaceCacheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hidden_place_cache_id");

                    b.Property<string>("BusinessStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("OPERATIONAL")
                        .HasColumnName("business_status");

                    b.Property<string>("CacheGridKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cache_grid_key");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fetched_at_utc");

                    b.Property<string>("FormattedAddress")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("formatted_address");

                    b.Property<string>("GoogleMapsUri")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("google_maps_uri");

                    b.Property<double>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("NationalPhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("national_phone_number");

                    b.Property<bool>("PassedQualityGate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("passed_quality_gate");

                    b.Property<string>("PhotosJson")
                        .HasColumnType("json")
                        .HasColumnName("photos_json");

                    b.Property<string>("PlaceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("place_id");

                    b.Property<int?>("PriceLevel")
                        .HasColumnType("int")
                        .HasColumnName("price_level");

                    b.Property<string>("PrimaryType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("primary_type");

                    b.Property<double?>("Rating")
                        .HasColumnType("double")
                        .HasColumnName("rating");

                    b.Property<string>("RegularOpeningHoursJson")
                        .HasColumnType("json")
                        .HasColumnName("regular_opening_hours_json");

                    b.Property<int>("UserRatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("user_rating_count");

                    b.Property<string>("WebsiteUri")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("website_uri");

                    b.HasKey("HiddenPlaceCacheId")
                        .HasName("pk_hidden_place_cache");

                    b.HasIndex("CacheGridKey", "PlaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_hidden_place_cache_cache_grid_key_place_id");

                    b.ToTable("hidden_place_cache", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.HiddenPlaceSuppression", b =>
                {
                    b.Property<int>("HiddenPlaceSuppressionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hidden_place_suppression_id");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PlaceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("place_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reason");

                    b.Property<int>("ReportCount")
                        .HasColumnType("int")
                        .HasColumnName("report_count");

                    b.Property<DateTime>("SuppressedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("suppressed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("HiddenPlaceSuppressionId")
                        .HasName("pk_hidden_place_suppression");

                    b.HasIndex("PlaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_hidden_place_suppression_place_id");

                    b.ToTable("hidden_place_suppression", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("token_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId")
                        .HasName("pk_password_reset_token");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_prt_user_id");

                    b.ToTable("password_reset_token", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.Place", b =>
                {
                    b.Property<string>("PlaceId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("place_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("address");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("PlaceId")
                        .HasName("pk_places");

                    b.ToTable("places", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.PlacePhoto", b =>
                {
                    b.Property<int>("PlacePhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("place_photo_id");

                    b.Property<string>("Attribution")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("attribution");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PhotoReference")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("photo_reference");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("PlaceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("place_id");

                    b.HasKey("PlacePhotoId")
                        .HasName("pk_place_photo");

                    b.HasIndex("PlaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_place_photo_place_id");

                    b.ToTable("place_photo", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.Post", b =>
                {
                    b.Property<string>("PostId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("post_id");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("TaggedPlaceId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tagged_place_id");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int")
                        .HasColumnName("views_count");

                    b.HasKey("PostId")
                        .HasName("pk_community_posts");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_community_posts_author_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_community_posts_status");

                    b.HasIndex("TaggedPlaceId")
                        .HasDatabaseName("ix_community_posts_tagged_place_id");

                    b.ToTable("community_posts", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.PostComment", b =>
                {
                    b.Property<string>("CommentId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("comment_id");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("LikesCount")
                        .HasColumnType("int")
                        .HasColumnName("likes_count");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("post_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("CommentId")
                        .HasName("pk_community_post_comments");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_community_post_comments_author_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_community_post_comments_post_id");

                    b.ToTable("community_post_comments", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.PostImage", b =>
                {
                    b.Property<string>("ImageId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("image_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image_url");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("post_id");

                    b.HasKey("ImageId")
                        .HasName("pk_community_post_images");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_community_post_images_post_id");

                    b.HasIndex("PostId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_community_post_images_post_id_display_order");

                    b.ToTable("community_post_images", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.PostReaction", b =>
                {
                    b.Property<string>("ReactionId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("reaction_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("post_id");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("reaction_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ReactionId")
                        .HasName("pk_community_post_reactions");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_community_post_reactions_post_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_community_post_reactions_user_id");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_community_post_reactions_post_id_user_id");

                    b.ToTable("community_post_reactions", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.PostReport", b =>
                {
                    b.Property<string>("ReportId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("report_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("post_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reason");

                    b.Property<int>("ReporterId")
                        .HasColumnType("int")
                        .HasColumnName("reporter_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("ReportId")
                        .HasName("pk_community_post_reports");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_community_post_reports_post_id");

                    b.HasIndex("ReporterId")
                        .HasDatabaseName("ix_community_post_reports_reporter_id");

                    b.HasIndex("PostId", "ReporterId")
                        .IsUnique()
                        .HasDatabaseName("ix_community_post_reports_post_id_reporter_id");

                    b.ToTable("community_post_reports", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.RecommendedPlace", b =>
                {
                    b.Property<string>("SubmissionId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("submission_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("location_address");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<int>("SubmitterId")
                        .HasColumnType("int")
                        .HasColumnName("submitter_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("SubmissionId")
                        .HasName("pk_recommended_places");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_recommended_places_status");

                    b.HasIndex("SubmitterId")
                        .HasDatabaseName("ix_recommended_places_submitter_id");

                    b.ToTable("recommended_places", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.RecommendedPlaceReport", b =>
                {
                    b.Property<string>("ReportId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("report_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reason");

                    b.Property<int>("ReporterId")
                        .HasColumnType("int")
                        .HasColumnName("reporter_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("SubmissionId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("submission_id");

                    b.HasKey("ReportId")
                        .HasName("pk_recommended_place_reports");

                    b.HasIndex("ReporterId")
                        .HasDatabaseName("ix_recommended_place_reports_reporter_id");

                    b.HasIndex("SubmissionId", "ReporterId")
                        .IsUnique()
                        .HasDatabaseName("ix_recommended_place_reports_submission_id_reporter_id");

                    b.ToTable("recommended_place_reports", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.RecommendedPlaceVerification", b =>
                {
                    b.Property<string>("VerificationId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("verification_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("SubmissionId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("submission_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("VerificationId")
                        .HasName("pk_recommended_place_verifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_recommended_place_verifications_user_id");

                    b.HasIndex("SubmissionId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_recommended_place_verifications_submission_id_user_id");

                    b.ToTable("recommended_place_verifications", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.Review", b =>
                {
                    b.Property<long>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("review_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("GooglePlaceId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("google_place_id");

                    b.Property<decimal>("Rating")
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)")
                        .HasColumnName("rating");

                    b.Property<string>("RecommendPlaceId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("recommend_place_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ReviewId")
                        .HasName("pk_hidden_place_review");

                    b.HasIndex("GooglePlaceId")
                        .HasDatabaseName("ix_hidden_place_review_google_place_id");

                    b.HasIndex("RecommendPlaceId")
                        .HasDatabaseName("ix_hidden_place_review_recommend_place_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_hidden_place_review_user_id");

                    b.ToTable("hidden_place_review", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("pending_verification")
                        .HasColumnName("account_status");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasColumnType("enum('Male','Female','Prefer not to say')")
                        .HasColumnName("gender");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("profile_picture_url");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.UserSavedPost", b =>
                {
                    b.Property<string>("SavedId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("saved_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("post_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("SavedId")
                        .HasName("pk_user_saved_posts");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_user_saved_posts_post_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_saved_posts_user_id");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_saved_posts_post_id_user_id");

                    b.ToTable("user_saved_posts", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.UserSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("session_token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId")
                        .HasName("pk_user_session");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_session_user_id");

                    b.ToTable("user_session", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("ExploreMy.Api.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_verification_token_users_user_id");
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.FavouritePlace", b =>
                {
                    b.HasOne("ExploreMy.Api.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favourite_place_users_user_id");
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.FootTrackerLog", b =>
                {
                    b.HasOne("ExploreMy.Api.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_foot_tracker_log_places_place_id");

                    b.HasOne("ExploreMy.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_foot_tracker_log_users_user_id");

                    b.Navigation("Place");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("ExploreMy.Api.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_token_users_user_id");
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.Post", b =>
                {
                    b.HasOne("ExploreMy.Api.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_posts_users_author_id");

                    b.HasOne("ExploreMy.Api.Domain.Entities.Place", "TaggedPlace")
                        .WithMany()
                        .HasForeignKey("TaggedPlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_community_posts_places_tagged_place_id");

                    b.Navigation("Author");

                    b.Navigation("TaggedPlace");
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.PostComment", b =>
                {
                    b.HasOne("ExploreMy.Api.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_post_comments_users_author_id");

                    b.HasOne("ExploreMy.Api.Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_post_comments_community_posts_post_id");

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.PostImage", b =>
                {
                    b.HasOne("ExploreMy.Api.Domain.Entities.Post", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_post_images_community_posts_post_id");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.PostReaction", b =>
                {
                    b.HasOne("ExploreMy.Api.Domain.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_post_reactions_community_posts_post_id");

                    b.HasOne("ExploreMy.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_post_reactions_users_user_id");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.PostReport", b =>
                {
                    b.HasOne("ExploreMy.Api.Domain.Entities.Post", "Post")
                        .WithMany("Reports")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_post_reports_community_posts_post_id");

                    b.HasOne("ExploreMy.Api.Domain.Entities.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_post_reports_users_reporter_id");

                    b.Navigation("Post");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.RecommendedPlace", b =>
                {
                    b.HasOne("ExploreMy.Api.Domain.Entities.User", "Submitter")
                        .WithMany()
                        .HasForeignKey("SubmitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommended_places_users_submitter_id");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.RecommendedPlaceReport", b =>
                {
                    b.HasOne("ExploreMy.Api.Domain.Entities.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommended_place_reports_users_reporter_id");

                    b.HasOne("ExploreMy.Api.Domain.Entities.RecommendedPlace", "Place")
                        .WithMany("Reports")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommended_place_reports_recommended_places_submission_id");

                    b.Navigation("Place");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.RecommendedPlaceVerification", b =>
                {
                    b.HasOne("ExploreMy.Api.Domain.Entities.RecommendedPlace", "Place")
                        .WithMany("Verifications")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommended_place_verifications_recommended_places_submissio");

                    b.HasOne("ExploreMy.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommended_place_verifications_users_user_id");

                    b.Navigation("Place");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.Review", b =>
                {
                    b.HasOne("ExploreMy.Api.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hidden_place_review_users_user_id");
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.UserSavedPost", b =>
                {
                    b.HasOne("ExploreMy.Api.Domain.Entities.Post", "Post")
                        .WithMany("Saves")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_saved_posts_posts_post_id");

                    b.HasOne("ExploreMy.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_saved_posts_users_user_id");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("ExploreMy.Api.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_session_users_user_id");
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Images");

                    b.Navigation("Reactions");

                    b.Navigation("Reports");

                    b.Navigation("Saves");
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.RecommendedPlace", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("Verifications");
                });
#pragma warning restore 612, 618
        }
    }
}
