// <auto-generated />
using System;
using ExploreMy.Api.Persistence.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace explore_my_backend.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    partial class MySqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("token_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_used");

                    b.Property<string>("PendingEmail")
                        .HasColumnType("longtext")
                        .HasColumnName("pending_email");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId")
                        .HasName("pk_email_verification_token");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_email_verification_token_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_verification_token_user_id");

                    b.ToTable("email_verification_token", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.HiddenPlace", b =>
                {
                    b.Property<int>("HiddenPlaceCacheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hidden_place_cache_id");

                    b.Property<string>("BusinessStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("business_status");

                    b.Property<string>("CacheGridKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cache_grid_key");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fetched_at_utc");

                    b.Property<double>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<bool>("PassedQualityGate")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("passed_quality_gate");

                    b.Property<string>("PlaceId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("place_id");

                    b.Property<int?>("PriceLevel")
                        .HasColumnType("int")
                        .HasColumnName("price_level");

                    b.Property<string>("PrimaryType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("primary_type");

                    b.Property<double?>("Rating")
                        .HasColumnType("double")
                        .HasColumnName("rating");

                    b.Property<int>("UserRatingCount")
                        .HasColumnType("int")
                        .HasColumnName("user_rating_count");

                    b.HasKey("HiddenPlaceCacheId")
                        .HasName("pk_hidden_place_cache");

                    b.HasIndex("CacheGridKey", "PlaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_hidden_place_cache_cache_grid_key_place_id");

                    b.ToTable("hidden_place_cache", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("token_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_used");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId")
                        .HasName("pk_password_reset_token");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_token_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_token_user_id");

                    b.ToTable("password_reset_token", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("account_status");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("City")
                        .HasColumnType("longtext")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext")
                        .HasColumnName("gender");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("profile_picture_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.UserSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("session_token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId")
                        .HasName("pk_user_session");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_session_user_id");

                    b.ToTable("user_session", (string)null);
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("ExploreMy.Api.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_verification_token_users_user_id");
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("ExploreMy.Api.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_token_users_user_id");
                });

            modelBuilder.Entity("ExploreMy.Api.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("ExploreMy.Api.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_session_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
