// /// Draft data carried through the 4-step Recommend Place wizard:
// ///
// ///   STEP 1 — Place Details  (name / primaryType / description)
// ///   STEP 2 — Direct Map Location (fixed center pin → lat/lng)
// ///   STEP 3 — Location Preview
// ///   STEP 4 — Review → Submit → Success
// ///
// /// The draft is passed between wizard steps as go_router `extra` so no global
// /// state is needed. Location is represented ONLY by latitude + longitude
// /// (selected map coordinates) — no reverse-geocoded address is stored.
// class RecommendPlaceDraft {
//   final String name;
//   final String primaryType;
//   final String description;
//
//   /// Set in STEP 2 from the location under the fixed center marker.
//   double? latitude;
//   double? longitude;
//
//   RecommendPlaceDraft({
//     required this.name,
//     required this.primaryType,
//     required this.description,
//     this.latitude,
//     this.longitude,
//   });
//
//   /// True once STEP 2 has produced a usable location.
//   bool get hasLocation => latitude != null && longitude != null;
//
//   RecommendPlaceDraft copyWith({
//     double? latitude,
//     double? longitude,
//   }) {
//     return RecommendPlaceDraft(
//       name: name,
//       primaryType: primaryType,
//       description: description,
//       latitude: latitude ?? this.latitude,
//       longitude: longitude ?? this.longitude,
//     );
//   }
// }

/// Draft data carried through the 4-step Recommend Place wizard:
///
///   STEP 1 — Place Details
///   STEP 2 — Direct Map Location
///   STEP 3 — Location Preview
///   STEP 4 — Review → Submit → Success
///
/// The draft is passed between wizard steps as go_router `extra`.
/// No global state needed.
///
/// Location:
/// - latitude / longitude = currently selected map coordinates
///   (coordinates are the ONLY authoritative location data; no address is
///   stored or generated by the current coordinates-based design).
///
/// Photos:
/// - photoPaths stores locally selected image paths.
/// - Actual upload should happen during submission/upload flow.
class RecommendPlaceDraft {
  // ============================================================
  // STEP 1 — PLACE DETAILS
  // ============================================================

  final String name;
  final String primaryType;
  final String description;

  /// Price level selected by user.
  ///
  /// Expected values can be:
  /// 0, 1, 2, 3, 4
  /// or whatever values your UI/backend contract defines.
  final int? priceLevel;

  /// Business status selected/returned for this place.
  ///
  /// Example:
  /// OPERATIONAL
  /// CLOSED_TEMPORARILY
  final String? businessStatus;

  /// Optional best time information entered by user.
  final String? bestTime;

  /// Optional tips entered by user.
  final String? tips;

  /// Locally selected photos.
  ///
  /// Store file paths here until upload occurs.
  final List<String> photoPaths;

  // ============================================================
  // STEP 2 — LOCATION
  // ============================================================

  /// Latitude of currently selected map location.
  double? latitude;

  /// Longitude of currently selected map location.
  double? longitude;

  // No address field: the design is coordinates-only. Reverse geocoding is
  // NOT implemented and the database has no address column, so an address is
  // never generated or stored (see audit §9 / fix scope item 5).

  // ============================================================
  // EDIT MODE
  // ============================================================

  /// When set, the wizard is editing an EXISTING recommendation and the final
  /// submit performs an UPDATE (PUT) instead of a create (POST). The value is
  /// the `submission_id` of the recommendation being edited. Null = new place.
  final String? editingSubmissionId;

  // ============================================================
  // CONSTRUCTOR
  // ============================================================

  RecommendPlaceDraft({
    required this.name,
    required this.primaryType,
    required this.description,
    this.priceLevel,
    this.businessStatus,
    this.bestTime,
    this.tips,
    List<String>? photoPaths,
    this.latitude,
    this.longitude,
    this.editingSubmissionId,
  }) : photoPaths = List.unmodifiable(photoPaths ?? const []);

  // ============================================================
  // LOCATION STATE
  // ============================================================

  /// True once STEP 2 has produced usable coordinates.
  bool get hasLocation =>
      latitude != null && longitude != null;

  RecommendPlaceDraft copyWith({
    String? name,
    String? primaryType,
    String? description,
    int? priceLevel,
    String? businessStatus,
    String? bestTime,
    String? tips,
    List<String>? photoPaths,
    double? latitude,
    double? longitude,
    String? editingSubmissionId,
  }) {
    return RecommendPlaceDraft(
      name: name ?? this.name,
      primaryType: primaryType ?? this.primaryType,
      description: description ?? this.description,
      priceLevel: priceLevel ?? this.priceLevel,
      businessStatus: businessStatus ?? this.businessStatus,
      bestTime: bestTime ?? this.bestTime,
      tips: tips ?? this.tips,
      photoPaths: photoPaths ?? this.photoPaths,
      latitude: latitude ?? this.latitude,
      longitude: longitude ?? this.longitude,
      editingSubmissionId: editingSubmissionId ?? this.editingSubmissionId,
    );
  }
}