USE exploremy_dev;

-- One community group per Malaysian district — 144 state districts plus the
-- 3 Federal Territories (Kuala Lumpur, Labuan, Putrajaya), 147 rows total —
-- for local dev/testing of the Communication module at a nationwide scale
-- rather than the handful of sample groups in InsertCommunityData.sql.
-- District list per state: statoids.org (administrative level 2 divisions of
-- Malaysia, checked August 2025). Requires the `state` column added to
-- `community` (see CreateTable.sql) — needed to display "State, District" on
-- the community card and to filter Browse Community by state.
-- Run after InsertUserData.sql if you also want the seeded users pre-joined.
INSERT INTO community
    (name, description, area, state, image_url)
VALUES
    -- Johor
    ('Batu Pahat Community', 'General chat and local tips for the Batu Pahat area, Johor.', 'Batu Pahat', 'Johor', NULL),
    ('Johor Bahru Community', 'General chat and local tips for the Johor Bahru area, Johor.', 'Johor Bahru', 'Johor', NULL),
    ('Kluang Community', 'General chat and local tips for the Kluang area, Johor.', 'Kluang', 'Johor', NULL),
    ('Kota Tinggi Community', 'General chat and local tips for the Kota Tinggi area, Johor.', 'Kota Tinggi', 'Johor', NULL),
    ('Kulai Community', 'General chat and local tips for the Kulai area, Johor.', 'Kulai', 'Johor', NULL),
    ('Mersing Community', 'General chat and local tips for the Mersing area, Johor.', 'Mersing', 'Johor', NULL),
    ('Muar Community', 'General chat and local tips for the Muar area, Johor.', 'Muar', 'Johor', NULL),
    ('Pontian Community', 'General chat and local tips for the Pontian area, Johor.', 'Pontian', 'Johor', NULL),
    ('Segamat Community', 'General chat and local tips for the Segamat area, Johor.', 'Segamat', 'Johor', NULL),
    ('Tangkak Community', 'General chat and local tips for the Tangkak area, Johor.', 'Tangkak', 'Johor', NULL),
    -- Kedah
    ('Baling Community', 'General chat and local tips for the Baling area, Kedah.', 'Baling', 'Kedah', NULL),
    ('Bandar Baharu Community', 'General chat and local tips for the Bandar Baharu area, Kedah.', 'Bandar Baharu', 'Kedah', NULL),
    ('Kota Setar Community', 'General chat and local tips for the Kota Setar area, Kedah.', 'Kota Setar', 'Kedah', NULL),
    ('Kuala Muda Community', 'General chat and local tips for the Kuala Muda area, Kedah.', 'Kuala Muda', 'Kedah', NULL),
    ('Kubang Pasu Community', 'General chat and local tips for the Kubang Pasu area, Kedah.', 'Kubang Pasu', 'Kedah', NULL),
    ('Kulim Community', 'General chat and local tips for the Kulim area, Kedah.', 'Kulim', 'Kedah', NULL),
    ('Langkawi Community', 'General chat and local tips for the Langkawi area, Kedah.', 'Langkawi', 'Kedah', NULL),
    ('Padang Terap Community', 'General chat and local tips for the Padang Terap area, Kedah.', 'Padang Terap', 'Kedah', NULL),
    ('Pendang Community', 'General chat and local tips for the Pendang area, Kedah.', 'Pendang', 'Kedah', NULL),
    ('Pokok Sena Community', 'General chat and local tips for the Pokok Sena area, Kedah.', 'Pokok Sena', 'Kedah', NULL),
    ('Sik Community', 'General chat and local tips for the Sik area, Kedah.', 'Sik', 'Kedah', NULL),
    ('Yan Community', 'General chat and local tips for the Yan area, Kedah.', 'Yan', 'Kedah', NULL),
    -- Kelantan
    ('Bachok Community', 'General chat and local tips for the Bachok area, Kelantan.', 'Bachok', 'Kelantan', NULL),
    ('Gua Musang Community', 'General chat and local tips for the Gua Musang area, Kelantan.', 'Gua Musang', 'Kelantan', NULL),
    ('Jeli Community', 'General chat and local tips for the Jeli area, Kelantan.', 'Jeli', 'Kelantan', NULL),
    ('Kota Bharu Community', 'General chat and local tips for the Kota Bharu area, Kelantan.', 'Kota Bharu', 'Kelantan', NULL),
    ('Kuala Krai Community', 'General chat and local tips for the Kuala Krai area, Kelantan.', 'Kuala Krai', 'Kelantan', NULL),
    ('Machang Community', 'General chat and local tips for the Machang area, Kelantan.', 'Machang', 'Kelantan', NULL),
    ('Pasir Mas Community', 'General chat and local tips for the Pasir Mas area, Kelantan.', 'Pasir Mas', 'Kelantan', NULL),
    ('Pasir Puteh Community', 'General chat and local tips for the Pasir Puteh area, Kelantan.', 'Pasir Puteh', 'Kelantan', NULL),
    ('Tanah Merah Community', 'General chat and local tips for the Tanah Merah area, Kelantan.', 'Tanah Merah', 'Kelantan', NULL),
    ('Tumpat Community', 'General chat and local tips for the Tumpat area, Kelantan.', 'Tumpat', 'Kelantan', NULL),
    -- Melaka
    ('Alor Gajah Community', 'General chat and local tips for the Alor Gajah area, Melaka.', 'Alor Gajah', 'Melaka', NULL),
    ('Jasin Community', 'General chat and local tips for the Jasin area, Melaka.', 'Jasin', 'Melaka', NULL),
    ('Melaka Tengah Community', 'General chat and local tips for the Melaka Tengah area, Melaka.', 'Melaka Tengah', 'Melaka', NULL),
    -- Negeri Sembilan
    ('Jelebu Community', 'General chat and local tips for the Jelebu area, Negeri Sembilan.', 'Jelebu', 'Negeri Sembilan', NULL),
    ('Jempol Community', 'General chat and local tips for the Jempol area, Negeri Sembilan.', 'Jempol', 'Negeri Sembilan', NULL),
    ('Kuala Pilah Community', 'General chat and local tips for the Kuala Pilah area, Negeri Sembilan.', 'Kuala Pilah', 'Negeri Sembilan', NULL),
    ('Port Dickson Community', 'General chat and local tips for the Port Dickson area, Negeri Sembilan.', 'Port Dickson', 'Negeri Sembilan', NULL),
    ('Rembau Community', 'General chat and local tips for the Rembau area, Negeri Sembilan.', 'Rembau', 'Negeri Sembilan', NULL),
    ('Seremban Community', 'General chat and local tips for the Seremban area, Negeri Sembilan.', 'Seremban', 'Negeri Sembilan', NULL),
    ('Tampin Community', 'General chat and local tips for the Tampin area, Negeri Sembilan.', 'Tampin', 'Negeri Sembilan', NULL),
    -- Pahang
    ('Bentong Community', 'General chat and local tips for the Bentong area, Pahang.', 'Bentong', 'Pahang', NULL),
    ('Bera Community', 'General chat and local tips for the Bera area, Pahang.', 'Bera', 'Pahang', NULL),
    ('Cameron Highlands Community', 'General chat and local tips for the Cameron Highlands area, Pahang.', 'Cameron Highlands', 'Pahang', NULL),
    ('Jerantut Community', 'General chat and local tips for the Jerantut area, Pahang.', 'Jerantut', 'Pahang', NULL),
    ('Kuantan Community', 'General chat and local tips for the Kuantan area, Pahang.', 'Kuantan', 'Pahang', NULL),
    ('Lipis Community', 'General chat and local tips for the Lipis area, Pahang.', 'Lipis', 'Pahang', NULL),
    ('Maran Community', 'General chat and local tips for the Maran area, Pahang.', 'Maran', 'Pahang', NULL),
    ('Pekan Community', 'General chat and local tips for the Pekan area, Pahang.', 'Pekan', 'Pahang', NULL),
    ('Raub Community', 'General chat and local tips for the Raub area, Pahang.', 'Raub', 'Pahang', NULL),
    ('Rompin Community', 'General chat and local tips for the Rompin area, Pahang.', 'Rompin', 'Pahang', NULL),
    ('Temerloh Community', 'General chat and local tips for the Temerloh area, Pahang.', 'Temerloh', 'Pahang', NULL),
    -- Perak
    ('Bagan Datuk Community', 'General chat and local tips for the Bagan Datuk area, Perak.', 'Bagan Datuk', 'Perak', NULL),
    ('Batang Padang Community', 'General chat and local tips for the Batang Padang area, Perak.', 'Batang Padang', 'Perak', NULL),
    ('Hilir Perak Community', 'General chat and local tips for the Hilir Perak area, Perak.', 'Hilir Perak', 'Perak', NULL),
    ('Kampar Community', 'General chat and local tips for the Kampar area, Perak.', 'Kampar', 'Perak', NULL),
    ('Kerian Community', 'General chat and local tips for the Kerian area, Perak.', 'Kerian', 'Perak', NULL),
    ('Kinta Community', 'General chat and local tips for the Kinta area, Perak.', 'Kinta', 'Perak', NULL),
    ('Kuala Kangsar Community', 'General chat and local tips for the Kuala Kangsar area, Perak.', 'Kuala Kangsar', 'Perak', NULL),
    ('Larut dan Matang Community', 'General chat and local tips for the Larut dan Matang area, Perak.', 'Larut dan Matang', 'Perak', NULL),
    ('Manjung Community', 'General chat and local tips for the Manjung area, Perak.', 'Manjung', 'Perak', NULL),
    ('Muallim Community', 'General chat and local tips for the Muallim area, Perak.', 'Muallim', 'Perak', NULL),
    ('Perak Tengah Community', 'General chat and local tips for the Perak Tengah area, Perak.', 'Perak Tengah', 'Perak', NULL),
    ('Ulu Perak Community', 'General chat and local tips for the Ulu Perak area, Perak.', 'Ulu Perak', 'Perak', NULL),
    -- Perlis
    ('Perlis Community', 'General chat and local tips for the Perlis area, Perlis.', 'Perlis', 'Perlis', NULL),
    -- Pulau Pinang
    ('Barat Daya Community', 'General chat and local tips for the Barat Daya area, Pulau Pinang.', 'Barat Daya', 'Pulau Pinang', NULL),
    ('Seberang Perai Selatan Community', 'General chat and local tips for the Seberang Perai Selatan area, Pulau Pinang.', 'Seberang Perai Selatan', 'Pulau Pinang', NULL),
    ('Seberang Perai Tengah Community', 'General chat and local tips for the Seberang Perai Tengah area, Pulau Pinang.', 'Seberang Perai Tengah', 'Pulau Pinang', NULL),
    ('Seberang Perai Utara Community', 'General chat and local tips for the Seberang Perai Utara area, Pulau Pinang.', 'Seberang Perai Utara', 'Pulau Pinang', NULL),
    ('Timur Laut Community', 'General chat and local tips for the Timur Laut area, Pulau Pinang.', 'Timur Laut', 'Pulau Pinang', NULL),
    -- Sabah
    ('Beaufort Community', 'General chat and local tips for the Beaufort area, Sabah.', 'Beaufort', 'Sabah', NULL),
    ('Beluran Community', 'General chat and local tips for the Beluran area, Sabah.', 'Beluran', 'Sabah', NULL),
    ('Keningau Community', 'General chat and local tips for the Keningau area, Sabah.', 'Keningau', 'Sabah', NULL),
    ('Kinabatangan Community', 'General chat and local tips for the Kinabatangan area, Sabah.', 'Kinabatangan', 'Sabah', NULL),
    ('Kota Belud Community', 'General chat and local tips for the Kota Belud area, Sabah.', 'Kota Belud', 'Sabah', NULL),
    ('Kota Kinabalu Community', 'General chat and local tips for the Kota Kinabalu area, Sabah.', 'Kota Kinabalu', 'Sabah', NULL),
    ('Kota Marudu Community', 'General chat and local tips for the Kota Marudu area, Sabah.', 'Kota Marudu', 'Sabah', NULL),
    ('Kuala Penyu Community', 'General chat and local tips for the Kuala Penyu area, Sabah.', 'Kuala Penyu', 'Sabah', NULL),
    ('Kudat Community', 'General chat and local tips for the Kudat area, Sabah.', 'Kudat', 'Sabah', NULL),
    ('Kunak Community', 'General chat and local tips for the Kunak area, Sabah.', 'Kunak', 'Sabah', NULL),
    ('Lahad Datu Community', 'General chat and local tips for the Lahad Datu area, Sabah.', 'Lahad Datu', 'Sabah', NULL),
    ('Nabawan Community', 'General chat and local tips for the Nabawan area, Sabah.', 'Nabawan', 'Sabah', NULL),
    ('Papar Community', 'General chat and local tips for the Papar area, Sabah.', 'Papar', 'Sabah', NULL),
    ('Penampang Community', 'General chat and local tips for the Penampang area, Sabah.', 'Penampang', 'Sabah', NULL),
    ('Pitas Community', 'General chat and local tips for the Pitas area, Sabah.', 'Pitas', 'Sabah', NULL),
    ('Putatan Community', 'General chat and local tips for the Putatan area, Sabah.', 'Putatan', 'Sabah', NULL),
    ('Ranau Community', 'General chat and local tips for the Ranau area, Sabah.', 'Ranau', 'Sabah', NULL),
    ('Sandakan Community', 'General chat and local tips for the Sandakan area, Sabah.', 'Sandakan', 'Sabah', NULL),
    ('Semporna Community', 'General chat and local tips for the Semporna area, Sabah.', 'Semporna', 'Sabah', NULL),
    ('Sipitang Community', 'General chat and local tips for the Sipitang area, Sabah.', 'Sipitang', 'Sabah', NULL),
    ('Tambunan Community', 'General chat and local tips for the Tambunan area, Sabah.', 'Tambunan', 'Sabah', NULL),
    ('Tenom Community', 'General chat and local tips for the Tenom area, Sabah.', 'Tenom', 'Sabah', NULL),
    ('Tongod Community', 'General chat and local tips for the Tongod area, Sabah.', 'Tongod', 'Sabah', NULL),
    ('Tuaran Community', 'General chat and local tips for the Tuaran area, Sabah.', 'Tuaran', 'Sabah', NULL),
    ('Tawau Community', 'General chat and local tips for the Tawau area, Sabah.', 'Tawau', 'Sabah', NULL),
    -- Sarawak
    ('Asajaya Community', 'General chat and local tips for the Asajaya area, Sarawak.', 'Asajaya', 'Sarawak', NULL),
    ('Bau Community', 'General chat and local tips for the Bau area, Sarawak.', 'Bau', 'Sarawak', NULL),
    ('Belaga Community', 'General chat and local tips for the Belaga area, Sarawak.', 'Belaga', 'Sarawak', NULL),
    ('Betong Community', 'General chat and local tips for the Betong area, Sarawak.', 'Betong', 'Sarawak', NULL),
    ('Bintulu Community', 'General chat and local tips for the Bintulu area, Sarawak.', 'Bintulu', 'Sarawak', NULL),
    ('Dalat Community', 'General chat and local tips for the Dalat area, Sarawak.', 'Dalat', 'Sarawak', NULL),
    ('Daro Community', 'General chat and local tips for the Daro area, Sarawak.', 'Daro', 'Sarawak', NULL),
    ('Julau Community', 'General chat and local tips for the Julau area, Sarawak.', 'Julau', 'Sarawak', NULL),
    ('Kanowit Community', 'General chat and local tips for the Kanowit area, Sarawak.', 'Kanowit', 'Sarawak', NULL),
    ('Kapit Community', 'General chat and local tips for the Kapit area, Sarawak.', 'Kapit', 'Sarawak', NULL),
    ('Kuching Community', 'General chat and local tips for the Kuching area, Sarawak.', 'Kuching', 'Sarawak', NULL),
    ('Lawas Community', 'General chat and local tips for the Lawas area, Sarawak.', 'Lawas', 'Sarawak', NULL),
    ('Limbang Community', 'General chat and local tips for the Limbang area, Sarawak.', 'Limbang', 'Sarawak', NULL),
    ('Lubok Antu Community', 'General chat and local tips for the Lubok Antu area, Sarawak.', 'Lubok Antu', 'Sarawak', NULL),
    ('Lundu Community', 'General chat and local tips for the Lundu area, Sarawak.', 'Lundu', 'Sarawak', NULL),
    ('Marudi Community', 'General chat and local tips for the Marudi area, Sarawak.', 'Marudi', 'Sarawak', NULL),
    ('Matu Community', 'General chat and local tips for the Matu area, Sarawak.', 'Matu', 'Sarawak', NULL),
    ('Meradong Community', 'General chat and local tips for the Meradong area, Sarawak.', 'Meradong', 'Sarawak', NULL),
    ('Miri Community', 'General chat and local tips for the Miri area, Sarawak.', 'Miri', 'Sarawak', NULL),
    ('Mukah Community', 'General chat and local tips for the Mukah area, Sarawak.', 'Mukah', 'Sarawak', NULL),
    ('Pakan Community', 'General chat and local tips for the Pakan area, Sarawak.', 'Pakan', 'Sarawak', NULL),
    ('Samarahan Community', 'General chat and local tips for the Samarahan area, Sarawak.', 'Samarahan', 'Sarawak', NULL),
    ('Saratok Community', 'General chat and local tips for the Saratok area, Sarawak.', 'Saratok', 'Sarawak', NULL),
    ('Sarikei Community', 'General chat and local tips for the Sarikei area, Sarawak.', 'Sarikei', 'Sarawak', NULL),
    ('Selangau Community', 'General chat and local tips for the Selangau area, Sarawak.', 'Selangau', 'Sarawak', NULL),
    ('Serian Community', 'General chat and local tips for the Serian area, Sarawak.', 'Serian', 'Sarawak', NULL),
    ('Sibu Community', 'General chat and local tips for the Sibu area, Sarawak.', 'Sibu', 'Sarawak', NULL),
    ('Simunjan Community', 'General chat and local tips for the Simunjan area, Sarawak.', 'Simunjan', 'Sarawak', NULL),
    ('Song Community', 'General chat and local tips for the Song area, Sarawak.', 'Song', 'Sarawak', NULL),
    ('Sri Aman Community', 'General chat and local tips for the Sri Aman area, Sarawak.', 'Sri Aman', 'Sarawak', NULL),
    ('Tatau Community', 'General chat and local tips for the Tatau area, Sarawak.', 'Tatau', 'Sarawak', NULL),
    -- Selangor
    ('Gombak Community', 'General chat and local tips for the Gombak area, Selangor.', 'Gombak', 'Selangor', NULL),
    ('Klang Community', 'General chat and local tips for the Klang area, Selangor.', 'Klang', 'Selangor', NULL),
    ('Kuala Langat Community', 'General chat and local tips for the Kuala Langat area, Selangor.', 'Kuala Langat', 'Selangor', NULL),
    ('Kuala Selangor Community', 'General chat and local tips for the Kuala Selangor area, Selangor.', 'Kuala Selangor', 'Selangor', NULL),
    ('Petaling Community', 'General chat and local tips for the Petaling area, Selangor.', 'Petaling', 'Selangor', NULL),
    ('Sabak Bernam Community', 'General chat and local tips for the Sabak Bernam area, Selangor.', 'Sabak Bernam', 'Selangor', NULL),
    ('Sepang Community', 'General chat and local tips for the Sepang area, Selangor.', 'Sepang', 'Selangor', NULL),
    ('Ulu Langat Community', 'General chat and local tips for the Ulu Langat area, Selangor.', 'Ulu Langat', 'Selangor', NULL),
    ('Ulu Selangor Community', 'General chat and local tips for the Ulu Selangor area, Selangor.', 'Ulu Selangor', 'Selangor', NULL),
    -- Terengganu
    ('Besut Community', 'General chat and local tips for the Besut area, Terengganu.', 'Besut', 'Terengganu', NULL),
    ('Dungun Community', 'General chat and local tips for the Dungun area, Terengganu.', 'Dungun', 'Terengganu', NULL),
    ('Hulu Terengganu Community', 'General chat and local tips for the Hulu Terengganu area, Terengganu.', 'Hulu Terengganu', 'Terengganu', NULL),
    ('Kemaman Community', 'General chat and local tips for the Kemaman area, Terengganu.', 'Kemaman', 'Terengganu', NULL),
    ('Kuala Nerus Community', 'General chat and local tips for the Kuala Nerus area, Terengganu.', 'Kuala Nerus', 'Terengganu', NULL),
    ('Kuala Terengganu Community', 'General chat and local tips for the Kuala Terengganu area, Terengganu.', 'Kuala Terengganu', 'Terengganu', NULL),
    ('Marang Community', 'General chat and local tips for the Marang area, Terengganu.', 'Marang', 'Terengganu', NULL),
    ('Setiu Community', 'General chat and local tips for the Setiu area, Terengganu.', 'Setiu', 'Terengganu', NULL),
    -- Federal Territories
    ('Kuala Lumpur Community', 'General chat and local tips for the Kuala Lumpur area, Federal Territories.', 'Kuala Lumpur', 'Federal Territories', NULL),
    ('Labuan Community', 'General chat and local tips for the Labuan area, Federal Territories.', 'Labuan', 'Federal Territories', NULL),
    ('Putrajaya Community', 'General chat and local tips for the Putrajaya area, Federal Territories.', 'Putrajaya', 'Federal Territories', NULL);
